CREATE TABLE USERS(
    UNQID TEXT NOT NULL,
    EMAIL TEXT NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL,
    NICKNAME TEXT NOT NULL,
    FLAIR TEXT,
    ROLE TEXT DEFAULT 'user'
    IS_DELETED BOOL DEFAULT FALSE,
    BANNED_TILL TIMESTAMP,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE POSTS(
    UNQID TEXT NOT NULL,
    TITLE TEXT NOT NULL,
    LINK TEXT,
    THUMB TEXT,
    CONTENT TEXT,
    LIKED_COUNT INT DEFAULT 1,
    LIKED_BY TEXT [] DEFAULT '{}',
    AUTHOR_ID TEXT NOT NULL,
    AUTHOR_NICK TEXT,
    AUTHOR_FLAIR TEXT DEFAULT 'Silly Goose',
    IS_DELETED BOOL DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE TAGS(
    NAME TEXT NOT NULL,
    POST_ID TEXT NOT NULL,
    AUTHOR_ID TEXT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);

CREATE TABLE COMMENTS(
    UNQID TEXT PRIMARY KEY,
    LEVEL INT NOT NULL,
    POST_ID TEXT,
    PARENT_ID TEXT,
    children_ids TEXT [] DEFAULT '{}',
    CONTENT TEXT,
    AUTHOR_ID TEXT NOT NULL,
    AUTHOR_NICK TEXT,
    IS_DELETED BOOL DEFAULT FALSE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DELETED_AT TIMESTAMP
);
